create table stg_payers(
	payerID VARCHAR,
	name VARCHAR,
	ownership VARCHAR,
	address VARCHAR,
	city VARCHAR,
	stateHeadquartered VARCHAR,
	zip VARCHAR,
	phone VARCHAR,
	amountCovered VARCHAR,
	amountUnCovered VARCHAR,
	revenue VARCHAR,
	coveredEncounters VARCHAR,
	uncoveredEncounters VARCHAR,
	coveredMedications VARCHAR,
	uncoveredMedications VARCHAR,
	coveredprocedures VARCHAR,
	uncoveredprocedures VARCHAR,
    coveredimmunizations VARCHAR,
	uncoveredimmunizations VARCHAR,
	uniqueCustomers VARCHAR,
	qlosAvg VARCHAR,
	memberMonths VARCHAR,
	PRIMARY KEY(payerID)
);